file(READ "${BUILD_DIR}/compile_commands.json" commands)
string(JSON count LENGTH "${commands}")
math(EXPR last "${count} - 1")
foreach(index RANGE ${last})
  string(JSON command GET "${commands}" ${index} command)
  string(JSON source GET "${commands}" ${index} file)
  if(HISTORICAL_PACKAGE AND source MATCHES "\\.c$")
    if(NOT command MATCHES "${HISTORICAL_PACKAGE}" OR NOT command MATCHES " /X " OR
       NOT command MATCHES "14\\.26\\.28801" OR NOT command MATCHES "10\\.0\\.19041\\.0")
      message(FATAL_ERROR "Historical build escaped its pinned compiler/sysroot: ${command}")
    endif()
  endif()
  if(command MATCHES "ffmpeg\\.dir" AND source MATCHES "\\.c$")
    if(NOT command MATCHES "[-/]DCHROMIUM_NO_LOGGING" OR NOT command MATCHES "-flto=thin")
      message(FATAL_ERROR "FFmpeg must use CHROMIUM_NO_LOGGING and ThinLTO: ${command}")
    endif()
  endif()
endforeach()
file(GLOB_RECURSE all_objects "${BUILD_DIR}/*.c.obj")
foreach(target IN ITEMS ffmpeg opus)
  set(objects "${all_objects}")
  list(FILTER objects INCLUDE REGEX "/${target}\\.dir/")
  if(NOT objects)
    message(FATAL_ERROR "No C objects found for ${target}")
  endif()
  foreach(object IN LISTS objects)
    file(READ "${object}" magic LIMIT 4 HEX)
    if(NOT magic STREQUAL "4243c0de")
      message(FATAL_ERROR "Not LLVM bitcode (ThinLTO disabled?): ${object}")
    endif()
  endforeach()
endforeach()
